
export const MAX_LENGTH_EMBED_TITLE = 256;
export const MAX_LENGTH_EMBED_DESCRIPTION = 4096;
export const MAX_LENGTH_EMBED_FIELD_NAME = 256;
export const MAX_LENGTH_EMBED_FIELD_VALUE = 1024;
export const MAX_LENGTH_EMBED_FOOTER_TEXT = 2048;
export const MAX_LENGTH_EMBED_AUTHOR_TEXT = 256;
export const MAX_LENGTH_EMBED_TOTAL = 6000;
export const MAX_EMBED_FIELDS = 25;