root: true
ignorePatterns:
  - node_modules
  - .vscode
  - "*.json"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project:
    - ./tsconfig.json
plugins:
  - "@typescript-eslint"
  - sort-class-members
env:
  es6: true
extends:
  - eslint:recommended
  # - plugin:import/recommended
  # - plugin:import/typescript
  # - plugin:node/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  # - plugin:lodash/recommended
  # - prettier
rules:
  prefer-rest-params:
    - 0
  sort-class-members/sort-class-members:
    - 2
    - order:
        - "[static-properties]"
        - "[static-methods]"
        - "[properties]"
        - "[conventional-private-properties]"
        - "constructor"
        - "[methods]"
        - "[conventional-private-methods]"
      accessorPairPositioning: "getThenSet"
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  lodash/prefer-lodash-method:
    - 0
  lodash/import-scope:
    - 0
  lodash/prop-shorthand:
    - 0
  lodash/prefer-constant:
    - 0
  "@typescript-eslint/no-inferrable-types":
    - 0
    - error
